pipeline {
    agent {
        docker {
            image 'node:6-lpine'
            args '-p:3000:3000'
        }

        }
        stages
        {
            stage('Build')
            {
                step {
                    sh 'npm install'
                
            }
        }
    }
}
